name: Build and Test with Qt6 for VS2022

on:
  push:
    branches: [ "main" ]
env:
  SOLUTION_FILE_PATH: SimpleRustDesk.sln
  BUILD_CONFIGURATION: Release
  Qt_DIR: "C:\\Qt\\6.8.2\\msvc2022_64"  # 新增Qt目录变量

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install aqt
        run: pip install aqtinstall

      - name: Install Qt6
        run: |
          aqt install-qt windows desktop 6.8.2 win64_msvc2022_64 -m qtbase qtsvg qt5compat qtnetwork
          echo "Qt6_DIR=C:\\Qt\\6.8.2\\msvc2022_64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup MSBuild (VS2022)
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Solution
        run: |
          $env:Path = "C:\\Qt\\6.8.2\\msvc2022_64\\bin;$env:Path"
          msbuild /m /p:Configuration=$env:BUILD_CONFIGURATION /p:QtVsTools=true /p:Qt_DIR="$env:Qt_DIR" $env:SOLUTION_FILE_PATH