name: Build and Test with Qt6 for VS2022

on:
  push:
    branches: [ "main" ]
env:
  SOLUTION_FILE_PATH: SimpleRustDesk.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install aqt
        run: pip install aqtinstall

      - name: Install Qt6
        run: |
          # 指定输出目录为 C:\Qt，这样 Qt 会被安装到 C:\Qt\6.8.2\win64_msvc2022_64
          aqt install-qt windows desktop 6.8.2 win64_msvc2022_64 -m all --outputdir "C:\Qt"
          echo "Qt6_DIR=C:\\Qt\\6.8.2\\win64_msvc2022_64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Prepare QtMsBuild folder
        run: |
          # 先确保目标目录存在
          New-Item -ItemType Directory -Path "$Env:LOCALAPPDATA\QtMsBuild" -Force | Out-Null
          
          # 拷贝仓库里的 QtMsBuild 脚本到本地用户目录
          Copy-Item -Path "$Env:GITHUB_WORKSPACE\QtMsBuild\*" `
                    -Destination "$Env:LOCALAPPDATA\QtMsBuild\" `
                    -Recurse -Force
          
          # 设置环境变量 QtMsBuild，让后续 steps 的 MSBuild 都认识
          echo "QtMsBuild=$Env:LOCALAPPDATA\QtMsBuild" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Check qmake
        run: dir C:\Qt\6.8.2\win64_msvc2022_64\bin

      - name: Setup MSBuild (VS2022)
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Solution
        run: msbuild SimpleRustDesk.sln /m /p:Configuration=Release /p:Platform=x64 /p:QtInstallation="Qt_6_8_2" /p:QtInstallDir="C:\Qt\6.8.2\win64_msvc2022_64"
